services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3500:3500"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "5000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"
